# Generated by Django 4.0.3 on 2022-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='everside_nps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('REVIEW_ID', models.CharField(max_length=100)),
                ('MEMBER_ID', models.CharField(max_length=100)),
                ('NPSCLINIC', models.CharField(max_length=100)),
                ('SURVEYDATE', models.CharField(max_length=100)),
                ('SURVEY_MONTH', models.CharField(max_length=100)),
                ('SURVEY_YEAR', models.CharField(max_length=100)),
                ('SURVEYNUMBER', models.CharField(max_length=100)),
                ('NPS', models.IntegerField(max_length=100)),
                ('REASONNPSSCORE', models.CharField(max_length=100)),
                ('WHATDIDWELLWITHAPP', models.CharField(max_length=100)),
                ('WHATDIDNOTWELLWITHAPP', models.CharField(max_length=100)),
                ('HOUSEHOLD_ID', models.CharField(max_length=100)),
                ('MEMBER_CITY', models.CharField(max_length=100)),
                ('MEMBER_STATE', models.CharField(max_length=100)),
                ('MEMBER_ZIP', models.CharField(max_length=100)),
                ('CLINIC_ID', models.CharField(max_length=100)),
                ('CLINIC_STREET', models.CharField(max_length=100)),
                ('CLINIC_CITY', models.CharField(max_length=100)),
                ('CLINIC_STATE', models.CharField(max_length=100)),
                ('CLINIC_ZIP', models.CharField(max_length=100)),
                ('CLINIC_TYPE', models.CharField(max_length=100)),
                ('PROVIDER_NAME', models.CharField(max_length=100)),
                ('PROVIDERTYPE', models.CharField(max_length=100)),
                ('PROVIDER_CATEGORY', models.CharField(max_length=100)),
                ('CLIENT_ID', models.CharField(max_length=100)),
                ('CLIENT_NAICS', models.CharField(max_length=100)),
                ('sentiment_label', models.CharField(max_length=100)),
                ('nps_label', models.CharField(max_length=100)),
                ('CLIENT_NAME', models.CharField(max_length=100)),
                ('PARENT_CLIENT_NAME', models.CharField(max_length=100)),
                ('PARENT_CLIENT_ID', models.CharField(max_length=100)),
                ('TIMESTAMP', models.BigIntegerField()),
            ],
        ),
    ]
