# Generated by Django 4.0.3 on 2022-06-13 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_everside_nps_region_alter_everside_nps_nps'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('USERNAME', models.CharField(max_length=100, unique=True)),
                ('EMAIL', models.EmailField(max_length=254, unique=True)),
                ('PASSWORD', models.CharField(max_length=250)),
                ('USER_TYPE', models.CharField(max_length=3)),
            ],
        ),
    ]
