# Generated by Django 4.0.3 on 2022-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='TOKEN',
            field=models.CharField(default='0', max_length=300),
        ),
    ]
