# Generated by Django 4.0.3 on 2022-07-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_engagement_file_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='everside_nps',
            name='POLARITY_SCORE',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='everside_nps',
            name='TOPIC',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
