# Generated by Django 4.0.3 on 2022-07-11 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0007_procidertopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProciderTopic',
            new_name='providerTopic',
        ),
    ]
