# Generated by Django 4.0.3 on 2022-07-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0008_rename_procidertopic_providertopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='clinicTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLINIC_FULL_NAME', models.CharField(max_length=100)),
                ('NPSCLINIC', models.CharField(max_length=100)),
                ('POSITIVE_TOPIC', models.CharField(max_length=100)),
                ('NEGATIVE_TOPIC', models.CharField(max_length=100)),
            ],
        ),
    ]
