# Generated by Django 4.0.3 on 2022-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_clinictopic'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLIENT_NAME', models.CharField(max_length=100)),
                ('POSITIVE_TOPIC', models.CharField(max_length=100)),
                ('NEGATIVE_TOPIC', models.CharField(max_length=100)),
            ],
        ),
    ]
