# Generated by Django 4.0.3 on 2022-07-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0010_clienttopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='everside_nps',
            name='ENCOUNTER_REASON',
            field=models.CharField(default='', max_length=100),
        ),
    ]
