# Generated by Django 4.0.3 on 2022-08-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_everside_nps_encounter_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='everside_nps',
            name='MEMBER_PROVIDER_SCORE',
            field=models.FloatField(default=0),
        ),
    ]
