# Generated by Django 4.0.3 on 2022-08-26 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_everside_nps_member_provider_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='everside_nps',
            name='CLIENT_NAICS',
        ),
    ]
